#
# Module manifest for module 'PSApplicationInsights'
# Generated by: Jos Verlinde
# Generated on: 17-10-2016
#

@{
    # Script module associated with this manifest.
    RootModule = 'PSAppInsights'
    ModuleVersion = '0.7.4'

    # ID used to uniquely identify this module
    GUID = '1706beeb-bb2f-4a51-b1fd-f972e62f4d2d'

    # Author of this module
    Author = 'Jos Verlinde [MSFT]'
    CompanyName = 'Microsoft'
    Copyright = '(c) 2016 Jos Verlinde. All rights reserved.'
    Description = 'Simplay add Application Insights to PowerShell to get basic and advanced tracing to gain insight to how your scripts are actually working, including errors and functional usage'

    # AppInsights Module is dependent on .Net 4.5
    DotNetFrameworkVersion = '4.5'

    # not tested on anyting lower than 4.0
    PowerShellVersion = '4.0'

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @(  
        #Application Insights Dlls that are needed for the exposed functionality 
        #base AI Service 
        '.\Microsoft.ApplicationInsights.2.2.0\lib\net45\Microsoft.ApplicationInsights.dll',
        #AI For fat clients 
        '.\Microsoft.ApplicationInsights.WindowsServer.2.2.0\lib\net45\Microsoft.AI.WindowsServer.dll',
        #AI based on perfcounters 
        '.\Microsoft.ApplicationInsights.PerfCounterCollector.2.2.0\lib\net45\Microsoft.AI.PerfCounterCollector.dll',
        # Tracking of dependencies 
        '.\Microsoft.ApplicationInsights.Agent.Intercept.2.0.7\lib\net45\Microsoft.AI.Agent.Intercept.dll',
        '.\Microsoft.ApplicationInsights.DependencyCollector.2.2.0\lib\net45\Microsoft.AI.DependencyCollector.dll',

    #   '.\Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.2.2.0\lib\net45\Microsoft.AI.ServerTelemetryChannel.dll', #not (yet) used
        #And the additional powershell modules 
        '.\AIPerformanceCollector.psm1',
        '.\AIDependency.psm1',
        '.\AIException.psm1',                   
        '.\AITrackMetrics.psm1',
        '.\AITrace.psm1',
        '.\AIEvent.psm1',
    #   '.\AIOperation.psm1',
    #   '.\AIPageView.psm1',             #Not relevant to PowerShell Client
        '.\HelperFunctions.psm1'
    )

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = '*'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = '*'

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = '*'


    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('Tracing','ApplicationInsights')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/Josverl/Connect-O365/raw/master/License'

            # A URL to the main website for this project.
            # ProjectUri = ''
            # A URL to an icon representing this module.
            IconUri = 'https://raw.githubusercontent.com/Josverl/Connect-O365/master/Connect-O365'

            # ReleaseNotes of this module
        ReleaseNotes = @"
V0.7.4   Upgrade to ApplicationInSights 2.2.0 
V0.7.3   Add support to report Powershell call stack
V0.7.2   Add Convertto-hashtable
V0.7     Add Collection of Performance Counters, Update to PSGallery
V0.6.2   Add caller's script or module version information to start-AISession
V0.6.1   Automatically add caller information on new Session (Script,  Line Number )
V0.6.0.2 Resolve naming collision for get-hash 
V0.5     initial publication 
"@                         

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''



}

